# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hangman.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from hangman_logic import Hangman



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 816)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Q = QtWidgets.QPushButton(self.centralwidget)
        self.Q.setGeometry(QtCore.QRect(30, 560, 51, 41))
        self.Q.setObjectName("Q")
        self.W = QtWidgets.QPushButton(self.centralwidget)
        self.W.setGeometry(QtCore.QRect(90, 560, 51, 41))
        self.W.setObjectName("W")
        self.E = QtWidgets.QPushButton(self.centralwidget)
        self.E.setGeometry(QtCore.QRect(150, 560, 51, 41))
        self.E.setObjectName("E")
        self.R = QtWidgets.QPushButton(self.centralwidget)
        self.R.setGeometry(QtCore.QRect(210, 560, 51, 41))
        self.R.setObjectName("R")
        self.T = QtWidgets.QPushButton(self.centralwidget)
        self.T.setGeometry(QtCore.QRect(270, 560, 51, 41))
        self.T.setObjectName("T")
        self.Y = QtWidgets.QPushButton(self.centralwidget)
        self.Y.setGeometry(QtCore.QRect(330, 560, 51, 41))
        self.Y.setObjectName("Y")
        self.U = QtWidgets.QPushButton(self.centralwidget)
        self.U.setGeometry(QtCore.QRect(390, 560, 51, 41))
        self.U.setObjectName("U")
        self.I = QtWidgets.QPushButton(self.centralwidget)
        self.I.setGeometry(QtCore.QRect(450, 560, 51, 41))
        self.I.setObjectName("I")
        self.O = QtWidgets.QPushButton(self.centralwidget)
        self.O.setGeometry(QtCore.QRect(510, 560, 51, 41))
        self.O.setObjectName("O")
        self.P = QtWidgets.QPushButton(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(570, 560, 51, 41))
        self.P.setObjectName("P")
        self.A = QtWidgets.QPushButton(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(60, 610, 51, 41))
        self.A.setObjectName("A")
        self.S = QtWidgets.QPushButton(self.centralwidget)
        self.S.setGeometry(QtCore.QRect(120, 610, 51, 41))
        self.S.setObjectName("S")
        self.D = QtWidgets.QPushButton(self.centralwidget)
        self.D.setGeometry(QtCore.QRect(180, 610, 51, 41))
        self.D.setObjectName("D")
        self.F = QtWidgets.QPushButton(self.centralwidget)
        self.F.setGeometry(QtCore.QRect(240, 610, 51, 41))
        self.F.setObjectName("F")
        self.G = QtWidgets.QPushButton(self.centralwidget)
        self.G.setGeometry(QtCore.QRect(300, 610, 51, 41))
        self.G.setObjectName("G")
        self.H = QtWidgets.QPushButton(self.centralwidget)
        self.H.setGeometry(QtCore.QRect(360, 610, 51, 41))
        self.H.setObjectName("H")
        self.J = QtWidgets.QPushButton(self.centralwidget)
        self.J.setGeometry(QtCore.QRect(420, 610, 51, 41))
        self.J.setObjectName("J")
        self.K = QtWidgets.QPushButton(self.centralwidget)
        self.K.setGeometry(QtCore.QRect(480, 610, 51, 41))
        self.K.setObjectName("K")
        self.L = QtWidgets.QPushButton(self.centralwidget)
        self.L.setGeometry(QtCore.QRect(540, 610, 51, 41))
        self.L.setObjectName("L")
        self.Z = QtWidgets.QPushButton(self.centralwidget)
        self.Z.setGeometry(QtCore.QRect(120, 660, 51, 41))
        self.Z.setObjectName("Z")
        self.X = QtWidgets.QPushButton(self.centralwidget)
        self.X.setGeometry(QtCore.QRect(180, 660, 51, 41))
        self.X.setObjectName("X")
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(240, 660, 51, 41))
        self.C.setObjectName("C")
        self.V = QtWidgets.QPushButton(self.centralwidget)
        self.V.setGeometry(QtCore.QRect(300, 660, 51, 41))
        self.V.setObjectName("V")
        self.B = QtWidgets.QPushButton(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(360, 660, 51, 41))
        self.B.setObjectName("B")
        self.N = QtWidgets.QPushButton(self.centralwidget)
        self.N.setGeometry(QtCore.QRect(420, 660, 51, 41))
        self.N.setObjectName("N")
        self.M = QtWidgets.QPushButton(self.centralwidget)
        self.M.setGeometry(QtCore.QRect(480, 660, 51, 41))
        self.M.setObjectName("M")
        self.new_game = QtWidgets.QPushButton(self.centralwidget)
        self.new_game.setGeometry(QtCore.QRect(140, 720, 151, 61))
        self.new_game.setObjectName("new_game")
        self.show_result = QtWidgets.QPushButton(self.centralwidget)
        self.show_result.setGeometry(QtCore.QRect(360, 720, 151, 61))
        self.show_result.setObjectName("show_result")
        self.hangman_pic = QtWidgets.QLabel(self.centralwidget)
        self.hangman_pic.setGeometry(QtCore.QRect(100, 150, 431, 261))
        self.hangman_pic.setText("")
        self.hangman_pic.setPixmap(QtGui.QPixmap("h1.png"))
        self.hangman_pic.setScaledContents(True)
        self.hangman_pic.setObjectName("hangman_pic")
        self.current_word = QtWidgets.QLabel(self.centralwidget)
        self.current_word.setGeometry(QtCore.QRect(0, 430, 631, 101))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.current_word.setFont(font)
        self.current_word.setText("")
        self.current_word.setTextFormat(QtCore.Qt.RichText)
        self.current_word.setScaledContents(True)
        self.current_word.setAlignment(QtCore.Qt.AlignCenter)
        self.current_word.setObjectName("current_word")
        self.end_game_message = QtWidgets.QLabel(self.centralwidget)
        self.end_game_message.setGeometry(QtCore.QRect(0, 20, 631, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.end_game_message.setFont(font)
        self.end_game_message.setScaledContents(True)
        self.end_game_message.setAlignment(QtCore.Qt.AlignCenter)
        self.end_game_message.setObjectName("end_game_message")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #connect buttons as a keyboard for hangman game
        self.keyboard = [self.Q, self.W, self.E, self.R, self.T, self.Y, self.U, self.I, self.O, self.P,
                    self.A, self.S, self.D, self.F, self.G, self.H, self.J, self.K, self.L, 
                    self.Z, self.X, self.C, self.V, self.B, self.N, self.M]
        for button in self.keyboard:
            button.clicked.connect(lambda state, i=button: self.letter_click(i))

        self.new_game.clicked.connect(lambda :self.newgame())
        self.show_result.clicked.connect(lambda :self.showresult())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hangman"))
        self.Q.setText(_translate("MainWindow", "Q"))
        self.W.setText(_translate("MainWindow", "W"))
        self.E.setText(_translate("MainWindow", "E"))
        self.R.setText(_translate("MainWindow", "R"))
        self.T.setText(_translate("MainWindow", "T"))
        self.Y.setText(_translate("MainWindow", "Y"))
        self.U.setText(_translate("MainWindow", "U"))
        self.I.setText(_translate("MainWindow", "I"))
        self.O.setText(_translate("MainWindow", "O"))
        self.P.setText(_translate("MainWindow", "P"))
        self.A.setText(_translate("MainWindow", "A"))
        self.S.setText(_translate("MainWindow", "S"))
        self.D.setText(_translate("MainWindow", "D"))
        self.F.setText(_translate("MainWindow", "F"))
        self.G.setText(_translate("MainWindow", "G"))
        self.H.setText(_translate("MainWindow", "H"))
        self.J.setText(_translate("MainWindow", "J"))
        self.K.setText(_translate("MainWindow", "K"))
        self.L.setText(_translate("MainWindow", "L"))
        self.Z.setText(_translate("MainWindow", "Z"))
        self.X.setText(_translate("MainWindow", "X"))
        self.C.setText(_translate("MainWindow", "C"))
        self.V.setText(_translate("MainWindow", "V"))
        self.B.setText(_translate("MainWindow", "B"))
        self.N.setText(_translate("MainWindow", "N"))
        self.M.setText(_translate("MainWindow", "M"))
        self.new_game.setText(_translate("MainWindow", "New Game"))
        self.show_result.setText(_translate("MainWindow", "Show Result"))
        self.end_game_message.setText(_translate("MainWindow", "Pressing a letter to start guessing!"))

    #create an observer pattern to monitor a button click event
    def __init__(self):
        self.observer = []
    
    def add_observer(self, obs):
        self.observer.append(obs)

 
    def letter_click(self, qbutton):
        for obs in self.observer:
            obs.update(qbutton.objectName())
        qbutton.setEnabled(False)

    def newgame(self):
        for obs in self.observer:
            obs.update('new_game')
        self.enable_letters()

    def enable_letters(self):
        for button in self.keyboard:
            button.setEnabled(True)


    def showresult(self):
        for obs in self.observer:
            obs.update('show_result')
        self.disable_letters()

    def disable_letters(self):
        for button in self.keyboard:
            button.setEnabled(False)        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
